{% set name = "zoxide" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ajeetdsouza/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8590d755b06daf79309fb1798da3e87c0cbb51b44becec0e7db09d4ae5d1f670

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses

test:
  commands:
    - zoxide --help

about:
  home: https://github.com/ajeetdsouza/zoxide
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A faster way to navigate your filesystem
  description: |
    zoxide is a blazing fast alternative to cd, inspired by z and z.lua. It keeps track of the directories you use most frequently, and uses a ranking algorithm to navigate to the best match.
  doc_url: https://github.com/ajeetdsouza/zoxide/blob/master/README.md
  dev_url: https://github.com/ajeetdsouza/zoxide

extra:
  recipe-maintainers:
    - daizeng1984
